"""Reproduce the S1 scaler used by TRAIN_SEHAT_revisi copy.ipynb, cell 63.

Run from the repository root: python scripts/generate_s1_scaler.py
The script also retrains the deterministic ExtraTrees model and compares its
root splits with the checked-in emlearn header before writing any constants.
"""

from pathlib import Path
import hashlib
import re

import numpy as np
import pandas as pd
from sklearn.ensemble import ExtraTreesRegressor


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "dataset_final_features_reprocessed.csv"
MODEL = ROOT / "et_hydration_model_S1.h"
OUTPUT = ROOT / "SEHAT_GSR_PPG_ESP32_ML" / "s1_scaler.h"
GSR = ["gsr_mean", "gsr_var", "gsr_entropy"]
PPG = ["mean_hr", "rmssd", "sdnn", "pnn50", "n_peaks"]
FEATURES = GSR + PPG + ["ppg_available"]


def prepare():
    df = pd.read_csv(DATA)
    df = df.loc[df.session_type.eq("fasting") & df.fasting_duration_hr.notna()].copy()
    df = df.reset_index(drop=True)
    record_start = pd.to_datetime(
        df.file.str.extract(r"^(\d{14})")[0], format="%Y%m%d%H%M%S"
    )
    fasting_start = record_start - pd.to_timedelta(df.fasting_duration_hr, unit="h")
    df["episode_id"] = (
        df.subject_id.astype(str) + "_"
        + fasting_start.dt.round("min").dt.strftime("%Y%m%d%H%M%S")
    )
    eligible = df.groupby("subject_id").episode_id.nunique()
    df = df.loc[df.subject_id.isin(eligible[eligible >= 2].index)].copy()
    for col in GSR + PPG:
        df[col] = df[col].astype(float)
    df["ppg_available"] = (
        df[PPG].notna().all(axis=1)
        & df[PPG].ne(-1).all(axis=1)
        & df.ppg_feature_valid.eq(True)
    ).astype("int8")
    return df.loc[df.subject_id.eq("S1")].copy()


def scaler_and_training_data(df):
    x = df[FEATURES].copy()
    valid_ppg = x.ppg_available.eq(1)
    means = []
    stds = []
    for col in GSR + PPG:
        values = x.loc[valid_ppg, col] if col in PPG else x[col]
        mean = values.mean()
        std = values.std()  # pandas default ddof=1
        if not np.isfinite(std) or std == 0:
            std = 1.0
        means.append(float(mean))
        stds.append(float(std))
        x[col] = ((x[col] - mean) / std).fillna(0.0)
        if col in PPG:
            x.loc[~valid_ppg, col] = 0.0
    if not np.isfinite(x.to_numpy(dtype=float)).all():
        raise ValueError("Non-finite S1 training features")
    return np.asarray(means), np.asarray(stds), x


def check_model(x, y):
    model = ExtraTreesRegressor(
        n_estimators=35, max_depth=8, min_samples_leaf=4, random_state=42
    ).fit(x, y)
    header = MODEL.read_text(encoding="utf-8")
    roots = re.findall(
        r"hydration_et_tree_\d+\([^)]*\)\s*\{\s*if \(features\[(\d+)\] < ([^)]*)\)",
        header,
    )
    if len(roots) != 35:
        raise ValueError(f"Expected 35 exported tree roots, got {len(roots)}")
    for i, (feature, threshold) in enumerate(roots):
        tree = model.estimators_[i].tree_
        if int(feature) != int(tree.feature[0]) or not np.isclose(
            float(threshold), tree.threshold[0], rtol=1e-6, atol=1e-6
        ):
            raise ValueError(
                f"Model header differs from reconstructed training at tree {i}: "
                f"exported=({feature}, {threshold}), "
                f"retrained=({tree.feature[0]}, {tree.threshold[0]})"
            )
    return model


def main():
    df = prepare()
    means, stds, x = scaler_and_training_data(df)
    check_model(x, df.fasting_duration_hr)
    digest = hashlib.sha256(DATA.read_bytes()).hexdigest()
    def values(items):
        return ",\n    ".join(f"{v:.17g}" for v in items)
    OUTPUT.write_text(
        "#pragma once\n\n"
        "// Generated by scripts/generate_s1_scaler.py from the revised notebook.\n"
        f"// Training CSV SHA-256: {digest}\n"
        f"// S1 fasting windows: {len(df)}; valid PPG windows: {int(x.ppg_available.sum())}.\n"
        "// The exported model's 35 root splits matched a deterministic retrain.\n"
        "namespace sehat_s1 {\n"
        f"constexpr double kMean[8] = {{\n    {values(means)}\n}};\n"
        f"constexpr double kStd[8] = {{\n    {values(stds)}\n}};\n"
        "}  // namespace sehat_s1\n",
        encoding="utf-8",
    )
    print(f"Verified 35 model roots; wrote {OUTPUT.relative_to(ROOT)}")
    print(f"S1 rows={len(df)}, valid PPG={int(x.ppg_available.sum())}, CSV SHA-256={digest}")


if __name__ == "__main__":
    main()
