#pragma once

// Generated by scripts/generate_s1_scaler.py from the revised notebook.
// Training CSV SHA-256: 7fd71394c995b22bc7e146d5551bdfdd3fac5fa18a7c3f9522aa80dee523d38b
// S1 fasting windows: 2487; valid PPG windows: 2160.
// The exported model's 35 root splits matched a deterministic retrain.
namespace sehat_s1 {
constexpr double kMean[8] = {
    4.6195829643954145,
    0.17862682034601393,
    1.942457875693441,
    111.35003311144918,
    54.717039876845121,
    115.84835827668967,
    42.15805109228522,
    52.638888888888886
};
constexpr double kStd[8] = {
    7.925908050017493,
    0.66853096565262216,
    0.29136955703512435,
    23.461282687165102,
    20.980549959270498,
    41.861661871748254,
    29.031490154316209,
    9.0722572425195285
};
}  // namespace sehat_s1
